from .account import Account as Account
from .auth import AuthKey as AuthKey
from .auth import AuthKeyType as AuthKeyType
from .map_data import MapData as MapData
from .mtp import MTP as MTP
from .storage import Serialize as Serialize
from .storage import Storage as Storage
from .storage_account import StorageAccount as StorageAccount
from .tdesktop import TDesktop as TDesktop
